#!/bin/bash
#
# wp-protect - Set attributes & permissions to protect Wordpress site files
#              (i.e., disable updates to core/plugins/themes)
#
# Author: Murray J. Brown <mjb@mjbrown.com>
#
# License: GPLv2 -- see license.txt file.
# WARNING: USE AT YOUR OWN RISK.
#

# Set wordpress directory
wpdir=$HOME/public_html
if [ "" != "$1" ]; then
    wpdir="$1";
fi

# Set user/group read & search permissions on all files
chmod -R ug=rX,o=rX $wpdir $wpdir/../wp-*

# Set user/group write perms in selected directories
chmod -f -R ug=rwX \
    $wpdir/wp-content/blogs.dir \
    $wpdir/wp-content/cache \
    $wpdir/wp-content/uploads

# Set files in all but selected directories immutable
chattr +i $wpdir/../wp-*
find $wpdir \
    -path $wpdir/wp-content/blogs.dir -prune -o \
    -path $wpdir/wp-content/cache -prune -o \
    -path $wpdir/wp-content/uploads -prune -o \
    -exec chattr +i {} \;

