#!/bin/bash
#
# wp-unprotect - Set attributes & permissions to unprotect Wordpress site files
#                (i.e., enable updates to core/plugins/themes)
#
# Author: Murray J. Brown <mjb@mjbrown.com>
#
# License: GPLv2 -- see license.txt file.
# WARNING: USE AT YOUR OWN RISK.
#

# Set wordpress directory
#wpdir=$HOME/public_html
wpdir=./wp-root
if [ "" != "$1" ]; then
    wpdir="$1";
fi

# Set files in all but selected directories mutable
chattr -i $wpdir/../wp-*
find $wpdir \
    -path $wpdir/wp-content/blogs.dir -prune -o \
    -path $wpdir/wp-content/cache -prune -o \
    -path $wpdir/wp-content/uploads -prune -o \
    -exec chattr -i {} \;

# Set user write permissions on all files
chmod -R u=rwX,go=rX $wpdir

# Set permissive file ownership
chown www-data:www-data $wpdir/../wp-*
chown -R www-data:www-data $wpdir

