#!/bin/bash
#
# wpdb-mvtables -  Export database tables for Wordpress site
#
# Synopsis: wpdb-mvtables <db-name> <site-prefix>
#
# Input:  stdin  - MySQL user information
# Ouput:  stdout - database SQL dump file
#
# Note: Underscore delimiter appended to prefix.
#
# Author: Murray J. Brown <mjb@mjbrown.com>
# License: GPLv2
#

# include utility functions
source wpdb_functions.sh


# Set dumptime
dumpTime=`/bin/date "+%Y-%m%d-%H%M"`;

#
# Parse parameters
#
#-- database name
if [ "" == "$1" ]; then
    echo "Usage: wpdb-export <db-name> <site-prefix>";
    exit 1;
fi
DbName="$1";

#-- site prefix
if [ "" == "$2" ]; then
    echo "Usage: wpdb-export <db-name> <site-prefix>";
    exit 1;
fi
sitePrefix="$2$DbPrefDelim";

if [ -f $sitePrefix.sql ]; then
    echo "Error: wpdb-export: dump file already exists -" $sitePrefix".sql";
    exit 1;
fi

# Get database authentication info
wpdb_credentials $DbName;

# Enumerate tables for existing site
unset DbTables;
wpdb_enum_tables $sitePrefix;

if [ 1 -ge ${#DbTables[@]} ]; then
    echo "Error: wpdb-export: database tables not found for site prefix -" $sitePrefix;
    exit 1;
fi

#
# Dump tables with given site prefix from named database
#
for tableName in ${DbTables[@]}; do
    /usr/bin/mysqldump --user=$DbUser --password=$DbPass $DbName $tableName >>$sitePrefix$dumpTime.sql;
done;

