#!/bin/bash
#
# wpdb-https - Show/Set selected configuration options for Wordpress-HTTPS plugin
#
# Synopsis: wpdb-urls <db_name> <site_prefix> [<fqdn> [<port>]]
#
# Input:  stdin  - MySQL user information
#                - database table dump file
# Output: MySQL  - database content
#
# Author: Murray J. Brown <mjb@mjbrown.com>
#
# License: GPLv2 -- see license.txt file.
# WARNING: USE AT YOUR OWN RISK.
#

# include utility functions
source wpdb_functions.sh

# Database & site parameters
DbUser=
DbPass=
DbName=
WpSite=

# Defined values for Wordpress-HTTPS plugin options
HTTPS_DEBUG=0
HTTPS_EXCLUSIVE_HTTPS=1
HTTPS_REMOVE_UNSECURE=0
HTTPS_SSL_ADMIN=1
HTTPS_SSL_HOST=https://
HTTPS_SSL_HOST_DIFF=1
HTTPS_SSL_HOST_SUBDOMAIN=0
HTTPS_SSL_PORT=443
HTTPS_SSL_PROXY=1

#
# Parse parameters
#
#-- database name
if [ "" == "$1" ]; then
    echo "Usage: wpdb-urls <db_name> <site_prefix> [<fqdn> [<port>]]";
    exit 1;
fi
DbName="$1";

#-- site prefix
if [ "" == "$2" ]; then
    echo "Usage: wpdb-urls <db_name> <site_prefix> [<fqdn> [<port>]]";
    exit 1;
fi
sitePrefix="$2$DbPrefDelim";

# Get database authentication info
wpdb_credentials $DbName;
dbTable=$DbName'.'$sitePrefix'options';

#-- site url 
if [ "" == "$3" ]; then
    #
    # Prepare MySQL query to show Wordpress-HTTPS plugin options for site
    #
	query=""
	query+="SELECT option_name,option_value FROM  $dbTable  WHERE option_name = 'wordpress-https_debug';"
	query+="SELECT option_name,option_value FROM  $dbTable  WHERE option_name = 'wordpress-https_exclusive_https';"
	query+="SELECT option_name,option_value FROM  $dbTable  WHERE option_name = 'wordpress-https_remove_unsecure';"
	query+="SELECT option_name,option_value FROM  $dbTable  WHERE option_name = 'wordpress-https_ssl_admin';"
	query+="SELECT option_name,option_value FROM  $dbTable  WHERE option_name = 'wordpress-https_ssl_host';"
	query+="SELECT option_name,option_value FROM  $dbTable  WHERE option_name = 'wordpress-https_ssl_host_diff';"
	query+="SELECT option_name,option_value FROM  $dbTable  WHERE option_name = 'wordpress-https_ssl_host_subdomain';"
	query+="SELECT option_name,option_value FROM  $dbTable  WHERE option_name = 'wordpress-https_ssl_port';"
	query+="SELECT option_name,option_value FROM  $dbTable  WHERE option_name = 'wordpress-https_ssl_proxy';"
else
    #
    # Prepare MySQL query to update Wordpress-HTTPS plugin options for site
    #
	fqdn=$3
    HTTPS_SSL_HOST+=`wpdb_url_host $fqdn`
	if [ "$HTTPS_SSL_PORT" != "$4" ]; then
		HTTPS_SSL_PORT="$4"
        HTTPS_SSL_HOST+=":$HTTPS_SSL_PORT"
	fi
    HTTPS_SSL_HOST+="/"

	query=""
	query+="UPDATE $dbTable SET option_value ='$HTTPS_DEBUG' WHERE option_name = 'wordpress-https_debug';"
	query+="UPDATE $dbTable SET option_value ='$HTTPS_EXCLUSIVE_HTTPS' WHERE option_name = 'wordpress-https_exclusive_https';"
	query+="UPDATE $dbTable SET option_value ='$HTTPS_REMOVE_UNSECURE' WHERE option_name = 'wordpress-https_remove_unsecure';"
	query+="UPDATE $dbTable SET option_value ='$HTTPS_SSL_ADMIN' WHERE option_name = 'wordpress-https_ssl_admin';"
	query+="UPDATE $dbTable SET option_value ='$HTTPS_SSL_HOST' WHERE option_name = 'wordpress-https_ssl_host';"
	query+="UPDATE $dbTable SET option_value ='$HTTPS_SSL_HOST_DIFF' WHERE option_name = 'wordpress-https_ssl_host_diff';"
	query+="UPDATE $dbTable SET option_value ='$HTTPS_SSL_HOST_SUBDOMAIN' WHERE option_name = 'wordpress-https_ssl_host_subdomain';"
	query+="UPDATE $dbTable SET option_value ='$HTTPS_SSL_PORT' WHERE option_name = 'wordpress-https_ssl_port';"
	query+="UPDATE $dbTable SET option_value ='$HTTPS_SSL_PROXY' WHERE option_name = 'wordpress-https_ssl_proxy';"
    
fi

# Invoke MySQL query
#echo "/usr/bin/mysql --user=$DbUser --password=$DbPass $DbName <<<$query;"
/usr/bin/mysql --user=$DbUser --password=$DbPass $DbName <<<$query;

