#!/bin/bash
#
# wpdb-move - Move/rename database tables for Wordpress site
#
# Synopsis: wpdb-move <db-name> <old-site-prefix> <new-site-prefix>
#
# Input:  stdin  - MySQL user information
# InOut:  MySQL  - database content
#
# Note: An underscore )'_') delimiter is appended to prefixes.
#
# Author: Murray J. Brown <mjb@mjbrown.com>
# License: GPLv2
#

# include utility functions
source wpdb_functions.sh

#
# Parse options
#
#-- database name
if [ "" == "$1" ]; then
    echo "Usage: wpdb-move <db-name> <old-site-prefix> <new-site-prefix>";
    exit 1;
fi
DbName="$1";

#-- old site prefix
if [ "" == "$2" ]; then
    echo "Usage: wpdb-move <db-name> <old-site-prefix> <new-site-prefix>";
    exit 1;
fi
oldSitePrefix="$2";
oldTablePrefix="$oldSitePrefix$DbPrefDelim";
 
#-- new site prefix
if [ "" == "$3" ]; then
    echo "Usage: wpdb-move <db-name> <old-site-prefix> <new-site-prefix>";
    exit 1;
fi
newSitePrefix="$3";
newTablePrefix="$newSitePrefix$DbPrefDelim";
 
# Get database authentication info
wpdb_credentials $DbName;

# Enumerate tables for existing site
unset DbTables;
wpdb_enum_tables $oldTablePrefix;

if [ 0 -ge ${#DbTables[@]} ]; then
    echo "Usage: wpdb-move: database tables not found for site prefix - " $oldSitePrefix;
    exit 1;
fi

#
# Prepare table rename SQL query to rename tables
#
query_rename="";
for tableName in ${DbTables[@]}; do
    if [ "$oldTablePrefix" == "${tableName:0:${#oldTablePrefix}}" ]; then
        newTableName=$newTablePrefix${tableName:${#oldTablePrefix}};
        query_rename+="ALTER TABLE $tableName RENAME TO $newTableName;";
    fi
done;

#
# Rename database tables
#
/usr/bin/mysql --user=$DbUser --password=$DbPass $DbName <<<$query_rename;

#
# Update metadata to refer to new site name
#
query_newmeta="UPDATE $newTablePrefix";
query_newmeta+="usermeta SET meta_key = REPLACE(meta_key, '$oldTablePrefix', '$newTablePrefix');";

/usr/bin/mysql --user=$DbUser --password=$DbPass $DbName <<<$query_newmeta;

