#!/bin/bash
#
# wpdb-urls - Show/Set URL(s) for Wordpress site
#
# Synopsis: wpdb-urls <db_name> <site_prefix> [<site-url> [<home-url>]]
#
# Input:  stdin  - MySQL user information
#                - database table dump file
# Output: MySQL  - database content
#
# Note: URLs must be given with http or https protocol, and '/' path specifiers:
#			http://<site_host>/ 
#		The [home] URL defaults to be same as for [siteurl]:
#
# Author: Murray J. Brown <mjb@mjbrown.com>
#
# License: GPLv2 -- see license.txt file.
# WARNING: USE AT YOUR OWN RISK.
#

# include utility functions
source wpdb_functions.sh

DbUser=root
DbPass=
DbName=
WpSite=

#
# Parse parameters
#
#-- database name
if [ "" == "$1" ]; then
    echo "Usage: wpdb-urls <db_name> <site_prefix> [<site_url> [<home-url>]]";
    exit 1;
fi
DbName="$1";

#-- site prefix
if [ "" == "$2" ]; then
    echo "Usage: wpdb-urls <db_name> <site_prefix> [<site_url> [<home-url>]]";
    exit 1;
fi
sitePrefix="$2$DbPrefDelim";

# Get database authentication info
wpdb_credentials $DbName;
dbTable=$DbName'.'$sitePrefix'options';

#-- site url 
if [ "" == "$3" ]; then
    #
    # Query site URLs in database
    #
    echo -n "siteurl ";
    /usr/bin/mysql --user=$DbUser --password=$DbPass <<EOF_QUERY_SITEURL
SELECT option_value FROM $dbTable WHERE option_name = 'siteurl';
EOF_QUERY_SITEURL
    echo "";
    echo -n "home ";
    /usr/bin/mysql --user=$DbUser --password=$DbPass <<EOF_QUERY_HOME
SELECT option_value FROM $dbTable WHERE option_name = 'home';
EOF_QUERY_HOME

else
    #
    #
    # Update site URLs in database
    #
    siteUrl="$3";
    homeUrl=$siteUrl;
    if [ "" != "$4" ]; then
        homeUrl="$4";
    fi
    #
    /usr/bin/mysql --user=$DbUser --password=$DbPass <<EOF_UPDATE_OPTIONS
UPDATE $dbTable SET option_value = '$siteUrl' WHERE option_name = 'siteurl';
UPDATE $dbTable SET option_value = '$homeUrl' WHERE option_name = 'home';
EOF_UPDATE_OPTIONS

fi
